accounts/urls.py
from django.urls import path,re_path, reverse
from django.contrib.auth.views import LogoutView

from .views import RegisterView, LoginView, guest_register_view 


app_name = 'accounts'
urlpatterns = [
    path('login/',LoginView.as_view(),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('register/',RegisterView.as_view(),name='register'),
    path('register/guest/',guest_register_view,name='guest'),
]

addresses/urls.py
from django.urls import path,re_path, reverse

from .views import (
        checkout_address_create_view,
        checkout_address_reuse_view,
        )

app_name = 'addresses'
urlpatterns = [
    path('checkout/address/create/', checkout_address_create_view, name='checkout_create'),
    path('checkout/address/reuse/', checkout_address_reuse_view, name='checkout_reuse'),
]

carts/urls.py
from django.urls import path,re_path, reverse

from .views import (
        cart_home, 
        cart_update, 
        checkout_home,
        checkout_done_view,
        cart_detail_api_view
        )

app_name = 'carts'
urlpatterns = [
    path('cart/', cart_home, name='home'),
    path('cart/update/', cart_update, name='update'),
    path('cart/checkout/', checkout_home, name='checkout'),
    path('cart/checkout/success/', checkout_done_view, name='success'),
    path('api/cart/', cart_detail_api_view, name='api'),
]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.urls import include, path
from django.contrib import admin
from django.views.generic import TemplateView

from billing.views import payment_method_view, payment_method_createview

from marketing.views import MarketingPreferenceUpdateView,MailchimpWebhookView
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home_page, name='home'),
    path('about/',views.about_page,name='about'),
    path('contact/',views.contact_page,name='contact'),
    path('billing/payment-method/',payment_method_view,name='billing-payment-method'),
    path('billing/payment-method/create/',payment_method_createview,name='billing-payment-method-endpoint'),
    path('settings/email/',MarketingPreferenceUpdateView.as_view(),name='marketing-pref'),
    path('webhooks/mailchimp/', MailchimpWebhookView.as_view(), name='webhooks-mailchimp'),
    path('', include('products.urls', namespace='products')),
    path('', include('search.urls', namespace='search')),
    path('', include('carts.urls', namespace='carts')),
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('addresses.urls', namespace='addresses')),
    
    #path('', include('orders.urls', namespace='order')),
    #path('<path/>'TemplateView.as_view(template_name='bootstrap/example.html')), 
    #path('checkout/address/create/', checkout_address_create_view, name='checkout_address_create'),
    #path('checkout/address/reuse/', checkout_address_reuse_view, name='checkout_address_reuse'),
]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/models.py
from decimal import Decimal
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save, post_save, m2m_changed

from products.models import Product


User = settings.AUTH_USER_MODEL

class CartManager(models.Manager):
        
    def new_or_get(self, request):
        cart_id = request.session.get("cart_id", None)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            new_obj = False
            cart_obj = qs.first()
            if request.user.is_authenticated and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            cart_obj = Cart.objects.new(user=request.user)
            new_obj = True
            request.session['cart_id'] = cart_obj.id
        return cart_obj, new_obj

    def new(self, user=None):
        user_obj = None
        if user is not None:
            if user.is_authenticated:
                user_obj = user
        return self.model.objects.create(user=user_obj)

class Cart(models.Model):
    user        = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    products    = models.ManyToManyField(Product, blank=True)
    subtotal    = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    total       = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    updated     = models.DateTimeField(auto_now=True)
    timestamp   = models.DateTimeField(auto_now_add=True)

    objects = CartManager()

    def __str__(self):
        return str(self.id)

def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        products = instance.products.all()
        total = 0
        for x in products:
            total += x.price
        if instance.subtotal != total:
            instance.subtotal = total
            instance.save()

m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)

def pre_save_cart_receiver(sender, instance, *args, **kwargs):
    if instance.subtotal > 0:
        # IVA ===== Must be in a configurtion file
        iva=0.13
        instance.total = instance.subtotal  + 10 #* 1.08
        instance.total = Decimal(instance.subtotal)+(Decimal(instance.subtotal) * Decimal(iva)) # tax
    else:
        instance.total = 0.00

pre_save.connect(pre_save_cart_receiver, sender=Cart)

carts/views.py
from django.conf import settings
from django.shortcuts import render,redirect
from django.http import JsonResponse

from accounts.forms import LoginForm, GuestForm
from accounts.models import GuestEmail
from addresses.forms import AddressForm
from addresses.models import Address

from billing.models import BillingProfile
from orders.models import Order
from products.models import Product
from .models import Cart

import stripe

STRIPE_SECRET_KEY = getattr(settings, "STRIPE_SECRET_KEY", "sk_test_51IRg1WJaIbGmBAOdAh0FxwTnhS7XLoTkHIFuYjejlHekiKBhmo2T9VOqeNE92uSs57nvYes798jhew9NX2L7TPu400Yz61ht4v")
STRIPE_PUB_KEY =  getattr(settings, "STRIPE_PUB_KEY", 'pk_test_51IRg1WJaIbGmBAOdsizxW00zGGS4MLJSUiNd4C1vj5hV4Sswp3JF4zFUdVSw6xZBPxn3990On1EIzRQnWGuEEQBh00mqsgm5UK')
stripe.api_key = STRIPE_SECRET_KEY

def cart_detail_api_view(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    products = [{
            "id": x.id,
            "url": x.get_absolute_url(),
            "name": x.name, 
            "price": x.price,
            "image": str(x.image),
            } 
            for x in cart_obj.products.all()]
    cart_data  = {"products": products, "subtotal": cart_obj.subtotal, "total": cart_obj.total}
    return JsonResponse(cart_data)

def cart_home(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    return render(request, "carts/home.html", {"cart":cart_obj})

def cart_update(request):
    product_id = request.POST.get('product_id')
    if product_id is not None:
        try:
            product_obj = Product.objects.get(id=product_id)
        except Product.DoesNotExist:
            #print("Show message to user, product is gone?")
            return redirect("carts:home")
        cart_obj, new_obj = Cart.objects.new_or_get(request)
        if product_obj in cart_obj.products.all():
            cart_obj.products.remove(product_obj)
            added = False
        else:
            cart_obj.products.add(product_obj) # cart_obj.products.add(product_id)
            added = True
        request.session['cart_items']=cart_obj.products.count()
        # return redirect(product_obj.get_absolute_url())
        ### look at Async Views.
        # if request.is_ajax(): # Asynchronous JavaScript And XML / JSON 
        # request.is_ajax() was deprecated in Django 3.1  instead use  below code
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':  
            json_data ={
                "added":added,
                "removed": not added,
                "cartItemCount":cart_obj.products.count()
            }
            return JsonResponse(json_data, status=200)

    return redirect("carts:home")

def checkout_home(request):
    cart_obj, cart_created = Cart.objects.new_or_get(request)
    order_obj = None
    if cart_created or cart_obj.products.count() == 0:
        return redirect("carts:home")
    login_form = LoginForm()
    guest_form = GuestForm()
    address_form = AddressForm()
    billing_address_id = request.session.get("billing_address_id", None)
    shipping_address_id = request.session.get("shipping_address_id", None)

    billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)
    address_qs = None
    has_card = False
    if billing_profile is not None:
        if request.user.is_authenticated:
            address_qs = Address.objects.filter(billing_profile=billing_profile)
        order_obj, order_obj_created = Order.objects.new_or_get(billing_profile, cart_obj)
        if shipping_address_id:
            order_obj.shipping_address = Address.objects.get(id=shipping_address_id)
            del request.session["shipping_address_id"]
        if billing_address_id:
            order_obj.billing_address = Address.objects.get(id=billing_address_id) 
            del request.session["billing_address_id"]
        if billing_address_id or shipping_address_id:
            order_obj.save()
        has_card = billing_profile.has_card

    if request.method == "POST":
        "check that order is done"
        is_prepared = order_obj.check_done()
        if is_prepared:
            did_charge, crg_msg = billing_profile.charge(order_obj)
            if did_charge:
                order_obj.mark_paid()
                request.session['cart_items'] = 0
                del request.session['cart_id']
                if not billing_profile.user:
                    '''
                    is this the best spot?
                    '''
                    billing_profile.set_cards_inactive()
                return redirect("carts:success")
            else:
                print(crg_msg)
                return redirect("carts:checkout")
    context = {
        "object": order_obj,
        "billing_profile": billing_profile,
        "login_form": login_form,
        "guest_form": guest_form,
        "address_form":address_form,
        "address_qs": address_qs,
        "has_card": has_card,
        "publish_key": STRIPE_PUB_KEY,
    }
    return render(request, "carts/checkout.html", context)


def checkout_done_view(request):
    return render(request, "carts/checkout-done.html", {})


    

carts/templates/carts/checkout-done.html
{% extends "base.html" %}


{% block content %}
<div class='col-6 mx-auto py-5 text-center'>
  <h1 class='display-1'>Thank you for your order!!!</h1>
</div>

{% endblock %}

carts/templates/carts/checkout.html
{% extends "base.html" %}

{% block content %}

{% if not billing_profile %}
    <div class='row text-center'>
    <div class='col-12 col-md-4'>
        <p class='lead'>Login</p>
        {% include 'accounts/snippets/form.html' with form=login_form next_url=request.build_absolute_uri %}
    </div>
    <div class='col-12 col-md-6'> 
        <p class='lead'>Continue as Guest</p>
        {% url "accounts:guest" as guest_register_url %}
        {% include 'accounts/snippets/form.html' with form=guest_form next_url=request.build_absolute_uri action_url=guest_register_url %}
    </div>
    </div>
{% else %}
    {% if not object.shipping_address %}
    <div class='row'>
        <div class='col-12'>
            <p class='lead'>Shipping Address</p>
            <hr/>
        </div>
        <div class='col-6'>
            {% url "addresses:checkout_create" as checkout_address_create %}
            {% include 'addresses/form.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create address_type='shipping' %}
        </div>
        <div class='col-6'>
            {% url 'addresses:checkout_reuse' as checkout_address_reuse %}
            {% include 'addresses/prev_addresses.html' with address_qs=address_qs next_url=request.build_absolute_uri address_type='shipping' action_url=checkout_address_reuse %}
        </div>
    </div>
    {% elif not object.billing_address %}
        <div class='row text-center'>
            <div class='col-12'>
                <p class='lead'>Billing Address</p>
                <hr/>
            </div>
            <div class='col-6'>
                {% url "addresses:checkout_create" as checkout_address_create %}
                {% include 'addresses/form.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create address_type='billing' %}
            </div>
            <div class='col-6'>
                {% url 'addresses:checkout_reuse' as checkout_address_reuse %}
                {% include 'addresses/prev_addresses.html' with address_qs=address_qs next_url=request.build_absolute_uri  address_type='billing' action_url=checkout_address_reuse %}
            </div>
        </div>
    {% else %}
        {% if not has_card %}
            <!-- enter credit card here -->
            <div class='stripe-payment-form' data-token='{{ publish_key }}' data-next-url='{{ request.build_absolute_uri }}' data-btn-title='Add Payment Method'></div>
        {% else %}
            <h1>Finalize Checkout</h1>
            <p>Cart Items: {% for product in object.cart.products.all %}{{ product }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
            <p>Shipping Address: {{ object.shipping_address.get_address }}</p>
            <p>Billing Address: {{ object.shipping_address.get_address }}</p>
            <p>Payment Method: {{ billing_profile.default_card }} (<a href="{{ billing_profile.get_payment_method_url }}?next={{ request.build_absolute_uri }}">Change</a>)</p>
            <p>Cart Total: {{ object.cart.total }}</p>
            <p>Shipping Total: {{ object.shipping_total }}</p>
            <p>Order Total: {{ object.total }}</p>
            <form class='form' method='POST' action="">{% csrf_token %}
                <button type='submit' class="btn btn-primary btn-sm">Checkout</button>
            </form>
        {% endif %}
    {% endif %}
{% endif %}

{% endblock %}

carts/templates/carts/home.html
{% extends "base.html" %}

{% block content %}
<h1>Cart</h1>

{%if cart.products.exists%}
<table class="table cart-table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Product Name</th>
        <th scope="col">Product Price</th>
        <th scope="col">Image</th>
      </tr>
    </thead>
    <tbody class='cart-body'>
         {%for product in cart.products.all%}
        <tr class='cart-product'>
          <th scope="row">{{forloop.counter}}</th>
          <td><a href='{{product.get_absolute_url}}'>{{product.title}}</a>
          
              {% include 'carts/snippets/remove-product.html' with product_id=product.id %}
          </td>
          <td>{{product.price}}</td>
          <td>product.image.url</td>
        </tr>
        {%endfor%}
       <tr>
        <td colspanscope="2"></td>
        <td><b> Subtotal </b> <span class='cart-subtotal'>{{cart.subtotal}}</span></td>
      </tr>
      <tr>
        <td colspanscope="2"></td>
        <td><b> Total </b> <span class='cart-total'>{{cart.total}}</span></td>
      </tr>
      <tr>
        <td colspan="2"></td>
        <td><a class="btn btn-primary btn-sm" href='{% url "carts:checkout" %}'>Checkout</a></td>
      </tr>
    </tbody>
  </table>
  <div class='cart-item-remove-form' style='display:none'>
    {% include 'carts/snippets/remove-product.html' %}
  </div>
  {%else%}
  <p class='lead'></p>Cart is empty</p>
  {%endif%}
{% endblock %}