accounts/urls.py
from django.urls import path,re_path, reverse
from django.contrib.auth.views import LogoutView

from .views import RegisterView, LoginView, guest_register_view 


app_name = 'accounts'
urlpatterns = [
    path('login/',LoginView.as_view(),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('register/',RegisterView.as_view(),name='register'),
    path('register/guest/',guest_register_view,name='guest'),
]

carts/urls.py
from django.urls import path,re_path, reverse

from .views import (
        cart_home, 
        cart_update, 
        checkout_home,
        checkout_done_view,
        cart_detail_api_view
        )

app_name = 'carts'
urlpatterns = [
    path('cart/', cart_home, name='home'),
    path('cart/update/', cart_update, name='update'),
    path('cart/checkout/', checkout_home, name='checkout'),
    path('cart/checkout/success/', checkout_done_view, name='success'),
    path('api/cart/', cart_detail_api_view, name='api'),
]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.urls import include, path
from django.contrib import admin
from django.views.generic import TemplateView

from billing.views import payment_method_view, payment_method_createview

from marketing.views import MarketingPreferenceUpdateView,MailchimpWebhookView
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home_page, name='home'),
    path('about/',views.about_page,name='about'),
    path('contact/',views.contact_page,name='contact'),
    path('billing/payment-method/',payment_method_view,name='billing-payment-method'),
    path('billing/payment-method/create/',payment_method_createview,name='billing-payment-method-endpoint'),
    path('settings/email/',MarketingPreferenceUpdateView.as_view(),name='marketing-pref'),
    path('webhooks/mailchimp/', MailchimpWebhookView.as_view(), name='webhooks-mailchimp'),
    path('', include('products.urls', namespace='products')),
    path('', include('search.urls', namespace='search')),
    path('', include('carts.urls', namespace='carts')),
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('addresses.urls', namespace='addresses')),
    
    #path('', include('orders.urls', namespace='order')),
    #path('<path/>'TemplateView.as_view(template_name='bootstrap/example.html')), 
    #path('checkout/address/create/', checkout_address_create_view, name='checkout_address_create'),
    #path('checkout/address/reuse/', checkout_address_reuse_view, name='checkout_address_reuse'),
]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,re_path, reverse
from .views import (
    ProductListView,
    product_list_view,
    ProductDetailView, 
    ProductDetailSlugView,
    ProductFeaturedListView,
)

app_name = 'products'
urlpatterns = [
    path('products/',ProductListView.as_view(),name='product'),
    path('productsf/',ProductFeaturedListView.as_view(),name='productf'),
    path('products/<int:pk>/',ProductDetailView.as_view(),name='detail'),
    path('products/<slug:slug>/',ProductDetailSlugView.as_view(),name='details'),
    re_path('products-fbv/',product_list_view)
]

templates/base/css.html
{% load static %}
<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

<!-- jQuery-Confirm v3 - https://craftpip.github.io/jquery-confirm/  -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">

<!-- Awesome CSS -->
<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' />

<!-- <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel='stylesheet' /> -->

<!-- Custom Stripe Styling -->
<link rel="stylesheet" href="{% static 'css/stripe-custom-style.css' %}">

templates/base/forms.html
{% extends "base.html" %}


{% block content %}
<div class='col-12 col-md-6 mx-auto'>
{% if title %}<h1 class='my-3'>{{ title }}</h1>{% endif %}
<form method='POST' action='{% if action_url %}{{ action_url }}{% endif %}'> {% csrf_token %}
    {% if next_url %}
    <input type='hidden' name='next' value='{{ next_url }}' />
    {% endif %}
  {{ form.as_p }}
  <button type='submit' class='btn btn-primary btn-sm'>Save</button>
</form>
</div>
{% endblock %}

templates/base/js.html
{% load static %}


<!-- JQuery cdn   - https://jquery.com/ -->
<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>

<!-- jQuery-Confirm v3 - https://craftpip.github.io/jquery-confirm/  -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>

<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>  -->

<!-- Awesome JS -->
<script src="https://kit.fontawesome.com/61ffc3599b.js" crossorigin="anonymous"></script>

<!-- Stripe JS -->
<script src="https://js.stripe.com/v3/"></script>

<!-- js Render -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jsviews/1.0.11/jsviews.min.js" integrity="sha512-nzeptB37xiXMYfCfY/IF7iDG13S82taErKCx2+bIWukARqZNu7Gea6W7/VYf5FerrcIpfB5RkrjR9hEyvLtO9A==" crossorigin="anonymous"></script>
{% include 'base/js_templates.html' %}

<!-- django csrf JS -->
<script src='{% static "js/csrf.ajax.js" %}'></script>

<!-- eCommerce Custom JS -->
<script src='{% static "js/ecommerce.js" %}'></script>

<!-- eCommerce Main JS -->
<script src='{% static "js/ecommerce.main.js" %}'></script>

templates/base/js_templates.html
{% verbatim %}
<!-- stripe template form -->
<script id="stripeTemplate" type="text/x-jsrender">
    <form class='payment-form' action="" method="post" id="payment-form" data-token='{{:publishKey}}' data-next-url='{{:nextUrl}}'>
  <div class="form-row">
    <!-- <label for="card-element">
      Credit or debit card
    </label> -->
    <div id="card-element" class='form-control'> 
      <!-- a Stripe Element will be inserted here. -->
    </div>

    <!-- Used to display form errors -->
    <div id="card-errors" role="alert"></div>
  </div>

  <button class='btn btn-primary my-3 btn-load'>{{:btnTitle }}</button>

    </form>

</script>
{% endverbatim %}

templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'about' as about_url %}
{% url 'contact' as contact_url %}
{% url 'products:product' as product_list_url %}
{% url 'products:productf' as featured_url %}
{% url 'accounts:login' as login_url %}
{% url 'accounts:logout' as logout_url %}
{% url 'accounts:register' as register_url %}
{% url 'carts:home' as cart_url %}


<nav class="navbar  navbar-expand-lg navbar-light bg-light">
    <!-- <div class="container-fluid"> -->
    <div class="container"> 
      <a class="navbar-brand" href="#">
        <img src="https://getbootstrap.com/docs/5.0/assets/brand/bootstrap-logo.svg" alt="" width="30" height="24">
      </a>
    <a class="navbar-brand" href="{{ home_url }}">{%if brand_name%} {{brand_name}} {%else %} eCommerce {%endif%} </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="nav nav-tabs me-auto mb-2 mb-lg-0">
        <!-- <ul class="navbar-nav me-auto mb-2 mb-lg-0"> -->
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{{ home_url }}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{product_list_url }}">Products</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{cart_url }}"><span class='navbar-cart-count'>{{request.session.cart_items}} </span><i class="fa fa-shopping-cart" aria-hidden="true"></i></a>
          </li>
          {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{{logout_url}}">Logout</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{{ login_url }}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ register_url }}">Register</a>
            </li>
          {% endif %}
        </ul>
        {%include 'search/snippets/search-form.html'%}
      </div>
    </div>
  </nav>

templates/base/navbar2.html
{% url 'home' as home_url %}
{% url 'about' as about_url %}
{% url 'contact' as contact_url %}
{% url 'products:product' as product_list_url %}
{% url 'products:productf' as featured_url %}
{% url 'acconts:login' as login_url %}
{% url 'accounts:logout' as logout_url %}
{% url 'register' as register_url %}
{% url 'cart:home' as cart_url %}


<nav class="navbar  navbar-expand-lg navbar-light bg-light">
    <!-- <div class="container-fluid"> -->
    <div class="container"> 
      <a class="navbar-brand" href="#">
        <img src="https://getbootstrap.com/docs/5.0/assets/brand/bootstrap-logo.svg" alt="" width="30" height="24">
      </a>
    <a class="navbar-brand" href="{{ home_url }}">{%if brand_name%} {{brand_name}} {%else %} eCommerce {%endif%} </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="nav nav-tabs me-auto mb-2 mb-lg-0">
        <!-- <ul class="navbar-nav me-auto mb-2 mb-lg-0"> -->
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{{ home_url }}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{product_list_url }}">Products</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{cart_url }}">{{request.session.cart_items}} <i class="fa fa-shopping-cart" aria-hidden="true"></i></a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Login
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="{{about_url}}">About</a></li>
                {% if request.user.is_authenticated %}
                    <li><a class="dropdown-item" href="{{logout_url}}">Logout</a></li>
                {% else %}
                    <li><a class="nav-link" href="{{ register_url }}">Register</a></li>
                    <li><a class="nav-link" href="{{ login_url }}">Login</a></li>
                {% endif %}
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{{contact_url}}">Contacts</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{featured_url}}" tabindex="-1" aria-disabled="true">Featured Products</a>
          </li>
        </ul>
        
        {%include 'search/snippets/search-form.html'%}
      </div>
    </div>
  </nav>